# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: intent.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'intent.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cintent.proto\x12\x06intent\"\x1d\n\rIntentRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\" \n\x0eIntentResponse\x12\x0e\n\x06intent\x18\x01 \x01(\t2Q\n\rIntentService\x12@\n\rPredictIntent\x12\x15.intent.IntentRequest\x1a\x16.intent.IntentResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'intent_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INTENTREQUEST']._serialized_start=24
  _globals['_INTENTREQUEST']._serialized_end=53
  _globals['_INTENTRESPONSE']._serialized_start=55
  _globals['_INTENTRESPONSE']._serialized_end=87
  _globals['_INTENTSERVICE']._serialized_start=89
  _globals['_INTENTSERVICE']._serialized_end=170
# @@protoc_insertion_point(module_scope)
